"""dogfood report rendering helpers.

Extracted from schedules.dogfood (loc-gate budget) — the pure report-markdown
renderer and the reports-dir ensure helper. No behavior change. The write/commit
seam (_write_and_commit) stays in schedules.dogfood so its REPORTS_DIR/JUGGLE_REPO
references remain patchable in the dogfood namespace by the dogfood tests.
"""
from __future__ import annotations

from schedules.common import REPORTS_DIR, today_str


def _build_report(since_date: str, agent_output: str, cost_total: float) -> str:
    today = today_str()
    return f"""\
# Juggle Self-Analysis — {today}

> Generated by `/schedule:dogfood` via Claude Code Routines.
> Data window: {since_date} to {today} (7 days)
> Agent: researcher, model: claude-sonnet-4-6
> LLM cost this run: ${cost_total:.4f}

{agent_output.strip()}
"""


def _ensure_reports_dir() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
