#!/usr/bin/env python3
"""Claude Code harness adapter — self-contained.

Owns everything Claude-Code-specific in one place:

  * launch       — ``claude --dangerously-skip-permissions`` (from
                   ``agent.claude_launch_command``), ``--model``, env scrub of
                   ``CLAUDE_PLUGIN_DATA`` to avoid plugin-DB fragmentation.
  * restriction  — per-role ``permissions.deny`` written to a JSON settings
                   overlay and passed via ``--settings <file>`` (a short, fixed
                   token that pastes reliably; layers ADDITIVELY over the host
                   settings hierarchy, never replacing it). Generated by
                   ``juggle_agent_settings``.
  * context      — the role anchor is injected by juggle's ``UserPromptSubmit``
                   hook, so ``decorate_task`` (inherited) is a no-op here.
  * capabilities — full hooks engine; tmux markers for the Claude TUI.
"""

import shlex

from juggle_harness import HarnessAdapter, _CLAUDE_DEFAULTS, register_adapter


class ClaudeCodeAdapter(HarnessAdapter):
    """Built-in Claude Code adapter: per-role denies via a ``--settings`` overlay."""

    def _restrictions_part(self, role: str | None, audit: bool) -> str:
        # Per-role denied tools (and any future per-role settings) are written to
        # a settings overlay file and passed via `--settings <path>` — one short,
        # fixed token that pastes reliably into the pane. Imported at call time so
        # tests patching `juggle_agent_settings.write_agent_overlay` take effect.
        import juggle_agent_settings as _jas

        overlay_path = _jas.write_agent_overlay(role)
        return "--settings " + shlex.quote(str(overlay_path))


register_adapter("claude", ClaudeCodeAdapter, defaults=_CLAUDE_DEFAULTS)
